# Cross-compile the native app for Windows x64 from Linux with clang-cl (see native/README.md).
# Set XWIN to the folder produced by `xwin splat` (it contains crt/ and sdk/).
if(NOT DEFINED ENV{XWIN})
    message(FATAL_ERROR "Set the XWIN environment variable to your xwin splat folder")
endif()
set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR AMD64)
set(XWIN $ENV{XWIN})
set(CMAKE_C_COMPILER clang-cl)
set(CMAKE_CXX_COMPILER clang-cl)
set(CMAKE_LINKER lld-link)
set(CMAKE_AR llvm-lib)
set(CMAKE_RC_COMPILER llvm-rc)
set(CMAKE_MT llvm-mt)
set(_inc "/imsvc ${XWIN}/crt/include /imsvc ${XWIN}/sdk/include/ucrt /imsvc ${XWIN}/sdk/include/um /imsvc ${XWIN}/sdk/include/shared /imsvc ${XWIN}/sdk/include/winrt /imsvc ${XWIN}/sdk/include/cppwinrt")
set(CMAKE_C_FLAGS_INIT "${_inc} -fuse-ld=lld-link -Wno-unused-command-line-argument -D_ALLOW_COMPILER_AND_STL_VERSION_MISMATCH")
set(CMAKE_CXX_FLAGS_INIT "${_inc} -fuse-ld=lld-link -Wno-unused-command-line-argument -D_ALLOW_COMPILER_AND_STL_VERSION_MISMATCH")
set(CMAKE_RC_FLAGS_INIT "-I ${XWIN}/sdk/include/um -I ${XWIN}/sdk/include/shared")
set(_lib "/libpath:${XWIN}/crt/lib/x86_64 /libpath:${XWIN}/sdk/lib/um/x86_64 /libpath:${XWIN}/sdk/lib/ucrt/x86_64")
set(CMAKE_EXE_LINKER_FLAGS_INIT "${_lib}")
set(CMAKE_SHARED_LINKER_FLAGS_INIT "${_lib}")
set(CMAKE_MODULE_LINKER_FLAGS_INIT "${_lib}")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_TRY_COMPILE_CONFIGURATION Release)
